# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.NullBooleanField()),
                ('pay_sum', models.FloatField()),
                ('pay_datetime', models.DateTimeField(auto_now_add=True)),
                ('pay_comment', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='payment_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_fullname', models.CharField(max_length=255)),
                ('cat_createtime', models.DateTimeField(auto_now_add=True)),
                ('cat_updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='upper_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30)),
                ('menu_link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Элемент Меню',
                'verbose_name_plural': 'Элементы Меню',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telesite.payment_category'),
        ),
    ]
