# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.BooleanField()),
                ('pay_sum', models.FloatField()),
                ('pay_datetime', models.DateTimeField()),
                ('pay_comment', models.CharField(max_length=200)),
            ],
        ),
    ]
