# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upper_menu',
            table='menu',
        ),
    ]
