# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesite', '0002_auto_20170609_1407'),
    ]

    operations = [
        migrations.RunSQL('ALTER DATABASE telebot DEFAULT CHARACTER SET utf8;'),
        migrations.RunSQL('ALTER TABLE payment DEFAULT CHARACTER SET utf8;'),
        migrations.RunSQL('ALTER TABLE payment CONVERT TO CHARACTER SET utf8;'),
    ]
