# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telesite', '0005_auto_20170609_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.NullBooleanField()),
                ('pay_sum', models.FloatField()),
                ('pay_datetime', models.DateTimeField(auto_now_add=True)),
                ('pay_comment', models.CharField(max_length=200)),
                ('pay_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telesite.payment_category')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),

    ]
