# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesite', '0006_auto_20170609_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelTable(
            name='payment_category',
            table='categoriez',
        ),
    ]
