# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesite', '0007_auto_20170613_1303'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='payment_category',
            table='categories',
        ),
    ]
