# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesite', '0008_auto_20170613_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='upper_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30)),
                ('menu_link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Элемент Меню',
                'verbose_name_plural': 'Элементы Меню',
            },
        ),
    ]
